### ISSUE TITLE
Async query methods should have proper typings

### ISSUE THREAD

**Issue by thom801** [ticruz38/graphql-codegen-svelte-apollo#20]
When using async queries all the typings for the query results are lost (casted as any). Would be nice if we could fix that and get proper types in there.

**Comment by thom801** [comment]
@ticruz38 happy to help on this one I just need a little help with how to compile the index.js file so I can test this out in our project. Let me know and I can update the README to help other devs. Thanks in advance!

**Comment by ticruz38** [comment]
You should only modify index.ts, and run `tsc index.ts`, to get the file in javascript.
I am not having problems with the types when using AsyncQuery... Can you share a snippet of your code?

**Comment by thom801** [comment]
Ha, I tried `npx tsc index.ts` yesterday and no luck but today it worked fine so... 🤷  👍 

Our code looks like this:

```graphql
type Comment {
  _id: ID!
  author: Author
  authorId: String
  authorName: String
  body: String
  createdAt: Date
  pinned: Boolean
  playlist: Playlist
  playlistId: String
  post: Post
  postId: String
  tutorial: Tutorial
  tutorialId: String
  updatedAt: Date
}

extend type Query {
  comments(
    offset: Int
    limit: Int
    postId: String
    playlistId: String
    tutorialId: String
    isSortReverse: Boolean
  ): [Comment]
}
```

```graphql
query comments($postId: String, $tutorialId: String, $playlistId: String, $limit: Int) {
  comments(limit: $limit, postId: $postId, playlistId: $playlistId, tutorialId: $tutorialId) {
    _id
    authorName
    author {
      _id
      photoId
      isAdmin
      isEditor
    }
    postId
    playlistId
    pinned
    tutorialId
    body
    createdAt
    updatedAt
  }
}
```

Config looks like this:

```yaml
...
  ../svelteui/src/lib/graphql/generated.ts:
    presetConfig:
      extension: .generated.ts
      folder: ./
      baseTypesPath: types/types.generated.ts
    config:
      clientPath: '$lib/config/ApolloClient'
      asyncQuery: true
    plugins:
      - typescript
      - typescript-operations
      - graphql-codegen-svelte-apollo
 ...
```

But then the TS type for Asynccomments() result looks like this:

```typescript
(alias) Asynccomments(options: Omit<QueryOptions<Exact<{
    postId?: string;
    tutorialId?: string;
    playlistId?: string;
    limit?: number;
}>, any>, "query">): any
```

Notice any as the return type instead of it being something like `{ data: { comments: Comment[] }}`

**Comment by thom801** [comment]
Generated code looks like this:

```graphql

export type CommentQuery = (
  { __typename?: 'Query' }
  & { comment?: Maybe<(
    { __typename?: 'Comment' }
    & Pick<Comment, '_id' | 'body' | 'updatedAt' | 'createdAt' | 'playlistId' | 'tutorialId' | 'postId' | 'authorName'>
    & { author?: Maybe<(
      { __typename?: 'Author' }
      & Pick<Author, '_id'>
    )> }
  )> }
);

export const Asynccomments = (
	options: Omit<
		QueryOptions<CommentsQueryVariables>,
		"query"
	>
) => {
	return client.query<CommentsQuery>({query: CommentsDoc, ...options})
}
```

**Comment by thom801** [comment]
Let me know if you see anything funky in our setup. I'm going to look at the example project and see how it's set up and see if I can spot anything different.

**Comment by thom801** [comment]
Ok @ticruz38 I found out what was happening was the apollo client for our setup was being imported from the core directory within `node_modules/@apollo/client/core/core.cjs`. We found we had to use that or apollo imports react into our project which was causing issues. Did you find a way around that?

For any others running into this issue this is our current band-aid solution:

```typescript
import type { ApolloClient as ApolloClientType, NormalizedCacheObject } from '@apollo/client'
import { ApolloClient, InMemoryCache, HttpLink, ApolloLink } from '@apollo/client/core/core.cjs'
...
const client: ApolloClientType<NormalizedCacheObject> = new ApolloClient({ ... apollo config ... })
export default client
```

**Comment by ticruz38** [comment]
yes, you can import everything like that, and React will not be there:
```
import { ApolloClient, InMemoryCache, ApolloLink } from '@apollo/client/core';
```

I will update the example

**Comment by mattwilson1024** [comment]
Just in case any extra context helps anybody, I had a similar problem and it was caused by me wrongly including a `.ts` suffix in the configuration option for `clientPath`. 

e.g. in codegen.yml I had:

```
generates:
  src/generated/graphql.ts:
    plugins:
      - "typescript"
      - "typescript-operations"
      - "graphql-codegen-svelte-apollo"
    config:
      clientPath: ../lib/apollo-client.ts
      asyncQuery: true
````

changing the `clientPath` to exclude the `.ts` fixed it so that I got proper strong typings for the results of each AsyncQuery:

```
clientPath: ../lib/apollo-client
```

My `src/lib/apollo-client.ts` file looks like this:

```
import { ApolloClient, InMemoryCache } from '@apollo/client/core';

const cache = new InMemoryCache({
  addTypename: true,
});

export default new ApolloClient({
  uri: 'http://localhost:3001/graphql',
  cache,
});
```
